CREATE DATABASE StudentCommunity

USE StudentCommunity

CREATE TABLE USERS(

	USERID INT PRIMARY KEY IDENTITY(1,1),
	USERNAME VARCHAR(50) NOT NULL UNIQUE,
	EMAIL NVARCHAR(60),
	PASSWORD NVARCHAR(40)
);

SELECT * FROM USERS

EXEC sp_rename 
    'USERS.USERNAME',
    'EMAIL1',
    'COLUMN';

EXEC sp_rename 
    'USERS.EMAIL1',
    'EMAIL',
    'COLUMN';